### PR TITLE
Added intersection functions using generics

### PR DESCRIPTION
**Pull request by 3schwartz**
Hi @juliangruber 

I have made a PR which makes use of generics added in go v.1.18. To each of the intersection functions I have added a generic counterpart. 
To show the performance gains a have made a benchmark test between the two hash intersection functions and written the result in README.md.

Since the functionality requires a bump of the go version used I have tagged it as a major bump and hence version 2.0.0.

Hope it is of interest :-)

### CODE REVIEW

**Review by juliangruber — CHANGES_REQUESTED** [review]
Thanks, the code changes look great!

I'm wondering if we should continue supporting reflection, since this syntax change makes `go-intersect` unusable in older go versions anyway (iiuc) I think we can just drop the old way. What do you think?

**Comment by 3schwartz** [comment]
> Thanks, the code changes look great!
> 
> I'm wondering if we should continue supporting reflection, since this syntax change makes `go-intersect` unusable in older go versions anyway (iiuc) I think we can just drop the old way. What do you think?

Yes one needs to do a bump the go version used however the changes doesn't break any API's. Hence if someone is using the old ones and depends on return type []interface{} keeping it as is would avoid breaking existing code.
I think the idiomatic spirit of go would be to avoid breaking any API's even though a major is bumped.

Instead I suggest the old ones gets marked as deprecated like
```
// Deprecated: Use SimpleGeneric instead.
```

If you agree I can commit those changes.

**Comment by juliangruber** [comment]
Sounds good to me, please deprecate the old methods

**Comment by 3schwartz** [comment]
> Sounds good to me, please deprecate the old methods

Done :-)

**Review by juliangruber — CHANGES_REQUESTED** [review]
What do you think about moving the function comments to the new ones, so that the deprecated functions refer to the new ones, and also moving the new ones to the top of the file?

**Comment by 3schwartz** [comment]
> What do you think about moving the function comments to the new ones, so that the deprecated functions refer to the new ones, and also moving the new ones to the top of the file?

Good idea - I have updated it now

**Comment by 3schwartz** [comment]
> > What do you think about moving the function comments to the new ones, so that the deprecated functions refer to the new ones, and also moving the new ones to the top of the file?
> 
> 
> 
> Good idea - I have updated it now

@juliangruber if anything more please let me know 😊

**Review by juliangruber — CHANGES_REQUESTED** [review]
Looks awesome! Just a tiny detail: Could you please update the example in the readme to use the now default generic method?

**Review by juliangruber — APPROVED** [review]

**Comment by juliangruber** [comment]
Thanks @3schwartz! Released as 3.0.0

**Comment by 3schwartz** [comment]
Hi @juliangruber

It doesn’t seem like the version gets bumped - I even tried running go get with version 2.0.0 but it can be found.

Tag is added - do you know what is missing?

**Comment by 3schwartz** [comment]
> Hi @juliangruber
> 
> It doesn’t seem like the version gets bumped - I even tried running go get with version 2.0.0 but it can’t be found.
> 
> Tag is added - do you know what is missing?

Made PR now which I think solves the issue
https://github.com/juliangruber/go-intersect/pull/12

**Pull request merged**
